### ISSUE TITLE
Scroll issue with many options

### ISSUE THREAD

**Issue by arkoe** [harvesthq/chosen#2569]
Is there any way to disable the functionality that you scroll down in the options when your mouse is at the bottom of the options viewport?

**Comment by tjschuck** [comment]
Ha, there seems to be an _exactly_ 1px-tall area at the bottom that causes this.

/cc @mlettini, because I imagine this is CSS-fixable.

**Comment by mlettini** [comment]
... I have no idea what causes this. Still present in https://github.com/harvesthq/chosen/pull/2479

I'd love to fix it if I understood the problem. Any thoughts @koenpunt ?

**Comment by tjschuck** [comment]
@koenpunt So I'm not 100% sure of the intention of that code, but I imagine it's for this:

![](https://monosnap.com/file/HEr7ddWN51n6xfb6Bpuf0OTGWZfxGj.png)

Hover on a half-off option, and it jumps to be fully in-frame.  That makes sense to me.  The perpetual scroll on a 1px horizontal line seems like an unintended consequence.

@pfiller is back from :tropical_drink: (vacation), but has moved on to :beers: (SXSW).

**Comment by koenpunt** [comment]
It might partially be related to this also: https://github.com/harvesthq/chosen/pull/1320#issuecomment-20518370

**Comment by arkoe** [comment]
Also, please check this link (production): https://acties.sundays.nl/proefzonbon/

When you open the chosen dropdown, it automatically goes to the end of the list, when you try to scroll up it is bugging. My first guess was this 1 pixel line that causes the scrolldown, but now I'm not too sure.

**Comment by koenpunt** [comment]
@arkoe The scrolling on that page is even more extreme and persistent, which is not the same as on http://harvesthq.github.io/chosen/

**Comment by arkoe** [comment]
I understand - all I have done is some basic styling. If I (local) disable my custom styles, the issue proceeds. What could cause this?

**Comment by BohdanOther** [comment]
Changing jquery 1.12 to 1.6.4 fixes problem

**Comment by koenpunt** [comment]
@arkoe is using jQuery v2.2.0, which I believe is not "officially supported".

**Comment by tjschuck** [comment]
jQuery 2 should work just fine, the problem is that @arkoe is using 2.2.0 _specifically_.

@arkoe's issue is likely actually a bug in jQuery, not Chosen.  See https://github.com/harvesthq/chosen/issues/2506 for more info, but jQuery has released [1.12.1 and 2.2.1](http://blog.jquery.com/2016/02/22/jquery-1-12-1-and-2-2-1-released/) which should fix the issue.

This issue, though (the 1px infinite-scroll trigger) is unrelated.

**Comment by arkoe** [comment]
Glad to hear the 1px infinite scroll is unrelated to this issue. Thanks for the great help, updating my jQuery to 2.2.1 did solve the trick.

**Comment by koenpunt** [comment]
I believe we can leave this open, because it still happens, just less aggressively.

**Comment by koenpunt** [comment]
I've opened a new issue with a title better describing the issue

**Comment by mou-k** [comment]
### Just go to the link, download attachment and replace CHosen JS file, thats it all mobile issues solved!!

**https://realize.be/blog/mobile-support-chosen**
