### ISSUE TITLE
html5 required attribute support?

### ISSUE THREAD

**Issue by pushinginertia** [harvesthq/chosen#515]
When chosen is initialized on a select input, it adds [style="display:none"] to the select tag and creates the various div tags it needs, as follows.

``` html
<select name="country" id="country" style="display: none; " class="chzn-done">
    <option selected="selected" value=""></option>
    ...
</select>
```

This is fine, but we have a problem if I add the html5 'required' attribute to my select tag, which produces the following markup after chosen initializes:

``` html
<select name="country" id="country" required="required" style="display: none; " class="chzn-done">
<option selected="selected" value=""></option>
...
</select>
```

The problem occurs when the user submits the form without selecting a value.  To the user, the browser seems to do nothing.  In fact, it's displaying an error message to the user to select a value, but because the CSS instructs the browser not to show the select element, the error message also doesn't appear.

This is happening in Chrome, I'm not sure about the behaviour of other browsers.

I haven't dug deep enough to suggest a solution, but this is an issue as we start to include html5 attributes in our forms.

**Comment by cortopy** [comment]
After a very long read, I thought I tried the suggestions submitted throughout the years. 

Unfortunately, I couldn't get the code by @christhomas to work. I invoke it within a submit function with no visible results (no errors either).

Good news is the new function by @ghiculescu works like a treat as I can still use the CDN chosen file and just use the function in my js file.

@DASPRiD @charettes what do you mean tab doesn't work with the modified function? It seems to be working for me

**Comment by andreialecu** [comment]
Easy enough to add tabindex: -1 to the select to @ghiculescu 's snippet, solving the tabbing problem.

Example: http://jsfiddle.net/hq7b426j/

**Comment by cortopy** [comment]
I could see the problem now! Your addition works great @andreialecu

**Comment by andreialecu** [comment]
There was one other addition needed by the way. On iPhone, or other unsupported devices, the fiddle wouldn't work properly. Chosen disables itself on iPhone and leaves the <select> unchanged, and the code in the fiddle above would hide it, leaving no way to interact with the select.

This fiddle fixes it (by adding a display: none check):
http://jsfiddle.net/hq7b426j/1/

**Comment by cortopy** [comment]
Ah that's even better!! Thanks! I'm still testing too, but I'll post if anything else comes up

**Comment by vidhyaprakash85** [comment]
@CaptainN please brief i have same issue. wr i need to put that code. i am using inspina theme from wrapbootstrap.

**Comment by CaptainN** [comment]
@vidhyaprakash85 I'm not sure what you mean. I had forked a long while ago, and wrote a pull request (#900) but the repos are out of sync now, and my fork is very out of date. You can findit here if it helps: https://github.com/adcSTUDIO/chosen

**Comment by vidhyaprakash85** [comment]
i am already using https://github.com/harvesthq/chosen how to do that :(

**Comment by TeLiXj** [comment]
@andreialecu your code works fine! thanks!!!

**Comment by DannyFeliz** [comment]
Thank @christhomas your code work great :dancer:

**Comment by weiserma** [comment]
Neither @christhomas or @ghiculescu worked for me using a multi-grouped select.  leaving it to server validation for now.

When I tried I the  @ghiculescu  patch, it worked except a scroll was displayed all the time, below the select box. 
When I tried the @christhomas  patch the popup appeared without the search box opening.

**Comment by doganmeh** [comment]
One more addition to @ghiculescu's snippent in case you need to call chosen twice such as:
```
target.find('select')
        .chosen('destroy')
        .chosen({disable_search_threshold: 10})
```
I just added !select.css('clip') to the 2nd if, so it does not remove the clip style it added on its 2nd visit:

```
$.fn.oldChosen = $.fn.chosen
$.fn.chosen = function(options) {
  var select = $(this)
    , is_creating_chosen = !!options

  if (is_creating_chosen && select.css('position') === 'absolute') {
    // if we are creating a chosen and the select already has the appropriate styles added
    // we remove those (so that the select hasn't got a crazy width), then create the chosen
    // then we re-add them later
    select.removeAttr('style')
  }

  var ret = select.oldChosen(options)

  // only act if the select has display: none, otherwise chosen is unsupported (iPhone, etc)
  if (is_creating_chosen && select.css('display') === 'none' && !select.css('clip')) {
    // https://github.com/harvesthq/chosen/issues/515#issuecomment-33214050
    // only do this if we are initializing chosen (no params, or object params) not calling a method
    select.attr('style','display:visible; position:absolute; clip:rect(0,0,0,0)');
    select.attr('tabindex', -1);
  }
  return ret
}```

**Comment by doganmeh** [comment]
I had to modify @ghiculescu 's script so I could call chosen twice as such:
```
target.find('select')
        .chosen('destroy')
        .chosen({disable_search_threshold: 10})
```
Otherwise, 2nd trip removed the style that was added in the first:
```
$.fn.oldChosen = $.fn.chosen
$.fn.chosen = function(options) {
  var select = $(this)
    , is_creating_chosen = !!options

    var style = 'display:visible; position:absolute; clip:rect(0,0,0,0);'

        if (is_creating_chosen && select.css('position') === 'absolute' && select.attr('style') != style) {
            // if we are creating a chosen and the select already has the appropriate styles added
            // we remove those (so that the select hasn't got a crazy width), then create the chosen
            // then we re-add them later
            select.removeAttr('style')
        }

        var ret = select.oldChosen(options)

        // only act if the select has display: none, otherwise chosen is unsupported (iPhone, etc)
        if (is_creating_chosen && select.css('display') === 'none') {
            // https://github.com/harvesthq/chosen/issues/515#issuecomment-33214050
            // only do this if we are initializing chosen (no params, or object params) not calling a method
            select.attr('style', style);
            select.attr('tabindex', -1);
        }
        return ret
}
```
I just added this extra condition to the 1st if: `&& select.attr('style') != style`

**Comment by J7mbo** [comment]
This doesn't work for me, I get: `Uncaught RangeError: Maximum call stack size exceeded`

**Comment by PhocaCz** [comment]
@doganmeh Works great in Chrome and mobile (with Chrome) but tested in Firefox 53.0 where it does not work

**Comment by PhocaCz** [comment]
Even this http://jsfiddle.net/hq7b426j/1/ does not work in Firefox 53.0

**Comment by PhocaCz** [comment]
Hmmm, but this seems more like a Firefox problem because if you click on the button more times, you will see that Firefox tries to display the message (but such is never rendered completely)

**Comment by bonifazzy** [comment]
I've used this solution. It is very simple and works perfect:

```
<style>
    select.submitted:invalid + .chosen-container{
        border-color: red !important;
    }
</style>
```

```
$('#yourSelector').chosen({
                no_results_text: "yourText",
                disable_search_threshold: 9,
                search_contains: true
                //your parameters
    }).on('invalid', function(){
        $(this).addClass('submitted');
    });
```

**Comment by jeromax2** [comment]
it seems that this doesn't work if you have chosen with multiple selections :
http://jsfiddle.net/jeromax/o5a8aogh/

**Comment by jeromax2** [comment]
I fixed it.
$.fn.oldChosen = $.fn.chosen
$.fn.chosen = function(options) {
  var select = $(this)
    , is_creating_chosen = !!options

  if (is_creating_chosen && select.css('position') === 'absolute') {
    // if we are creating a chosen and the select already has the appropriate styles added
    // we remove those (so that the select hasn't got a crazy width), then create the chosen
    // then we re-add them later
    select.removeAttr('style')
  }

  var ret = select.oldChosen(options)

  if (is_creating_chosen) {
    // https://github.com/harvesthq/chosen/issues/515#issuecomment-33214050
    // only do this if we are initializing chosen (no params, or object params) not calling a method
	  $(this).each(function(index){
		  if($(this)[0].multiple==true){
			  $(this).attr('style', 'display:visible; width:0px; height:0px; margin-top:25px; position:absolute; clip:rect(0,0,0,0)');
		  }else{
			  $(this).attr("style","display:block!important; position:absolute; clip:rect(0,0,0,0)");
		  }
	  })
  }
  return ret
}

**Comment by eriktelepovsky** [comment]
+1

Can somebody commit a fix for this? It's pretty old issue and very important functionality nowadays. Thank you.

**Comment by a-mawlawi** [comment]
Not working on latest version.

**Comment by thor-the-norseman** [comment]
This seems to be breaking angular.js form validation when using angular-chosen too.

**Comment by xcrap** [comment]
It's 2018 and we're still having the same issue. It's a hell how HTML standards cannot work properly and integrated with external plugins. Crazy times :)

**Comment by MPParsley** [comment]
This is breaking Drupal's chosen plugin as well. See https://www.drupal.org/project/chosen/issues/2705891

**Comment by valentinoli** [comment]
Couldn't find any proper solution to this other than a workaround:

```html
<div class="form__select">
  <select class="chosen">
    <!-- options -->
  </select>
</div>
```

```css
.form__select {
    position: relative;
}

.form__select select.chosen {
    display: block !important;
    height: 0 !important;
    pointer-events: none;
    outline: none;
    border-color: white;

    position: absolute;
    left: 35px !important;
    bottom: 0 !important;
}
```

**Comment by tripflex** [comment]
If you're using Chosen for all `select` elements, you can use this CSS to change make it visible (to DOM), but no opacity, no height, absolute position.

These CSS selectors target invalid select elements, with one of them targeting `multiple` adding a `15px` `margin-top` to center it on the multiselect elements.

    select:invalid {
    	height: 0px !important;
    	opacity: 0 !important;
    	position: absolute !important;
    	display: flex !important;
    }
    
    select:invalid[multiple] {
      	margin-top: 15px !important;
    }

Demo: http://jsfiddle.net/tripflex/2zdeu9oc/

**BUT REALLY** ... this should already be handled by the Chosen.JS lib

**Comment by jonathanbull** [comment]
Here's my workaround, if it's of any use:

```
            $('select').on('chosen:ready', function(evt, params, chosen) {
                $(this).css({'position': 'absolute', 'height': 0, 'opacity': 0}).show();
            });
```

**Comment by AndrewSouthpaw** [comment]
@jonathanbull can you show it within context? I tried your solution and it didn't work.

**Comment by Reforced** [comment]
@AndrewSouthpaw This is my code, fixs works fine for me :)

```
$("#select").val([]); // disable default selection by browser
$('#select').on('chosen:ready', function(evt, params, chosen) {
	$(this).css({'position': 'absolute', 'height': 0, 'opacity': 0}).show();
});
$("#select").chosen();
```

**Comment by eloyesp** [comment]
I'm using a slight different code (based on the code here):

``` js
$('.chosen-select').on("chosen:ready", function (evt, data) {
  $(this)
    .addClass('chosen_hidden')
    .prependTo(data.chosen.container)
    .show()
  })
  .chosen({width: '100%'})
```

``` css
.chosen_hidden {
  position: absolute;
  opacity: 0;
  top: 0;
  bottom: 0;
}
```

It does not handle the 'destroy' action, but it does position the error message nicely and seems to work on Firefox and chrome.

**Comment by jhedstrom** [comment]
There has been an open PR that resolves this, but I think it got lost since the other thread it targeted was closed. See #2594

**Comment by jonathanbull** [comment]
@jhedstrom would love to see that merged. Do you know if this library is still maintained?

**Comment by damsalem** [comment]
I used something similar to @eloyesp's solution above and shared that here:

https://github.com/harvesthq/chosen/pull/2594#issuecomment-714806139
